### ISSUE TITLE
Google is not allowing the app to authorize

### ISSUE THREAD

**Issue by tracec0d3** [bergercookie/syncall#26]
I enabled the less secure app section aslo, still google is not allowing to authenticate taskw_gcal_sync
<img width="798" alt="Screenshot 2021-05-13 at 3 59 22 PM" src="https://user-images.githubusercontent.com/48543431/118122770-5a225380-b404-11eb-9aa2-4a55f1864ed3.png">

**Comment by Petemir** [comment]
I am having the same issue. Perhaps it is possible to configure the application with personal tokens?

**Comment by bergercookie** [comment]
Yes it is. I'm planning to add instructional for this inthe next few days.
:)

**Comment by bergercookie** [comment]
Anyone else reaching this issue, there are now instructions to plug your own Calendar API key instead: https://github.com/bergercookie/taskw_gcal_sync/tree/master#override-calendar-api-key

**Comment by bergercookie** [comment]
Resubmitted app for review to Google

**Comment by DeadlySquad13** [comment]
Hello, thanks for your effort! Has review been passed? It's really annoying to recreate a token every 7 days.

I see our friends in gcalcli have had similar problems and solved it by migrating to a google auth library which helps making app verified it seems: https://github.com/insanum/gcalcli/pull/683
Maybe it would help in our case too? Sorry if I'm being ignorant and you already have this library integrated - just willing to help because want to see your cool app up and running)
