### ISSUE TITLE
[TW] Add ability to explicitly use scheduled dates instead of due dates 

### ISSUE THREAD

**Issue by bcohen44** [bergercookie/syncall#42]
Intitial sync puts TW tasks into my Calendar from the entry date.
How do I get the sync to happen for scheduled or due dates?

**Comment by bergercookie** [comment]
If it has a due date, it will use that. If there's no due date in the TW task it will use the entry date. What's a `scheduled` date?

**Comment by grovesteyn** [comment]
A scheduled date "Specifies the date after which a task can be
accomplished."  Basically it's when you want to start working on a task,
rather than the actual deadline. Very useful for multi-day tasks.
---
www.meridianeconomics.co.za
Office: +27 (0)21 200 5857
Mobile: +27 (0)83 379 1735
We are here: https://goo.gl/maps/5ebwTZWhefkPuugf7

**Comment by bergercookie** [comment]
This looks like a good addition. If I have time I'll have something for it soon :)

**Comment by bergercookie** [comment]
This is implemented among some other work I had been doing in this branch: https://github.com/bergercookie/taskwarrior-syncall/tree/gkeep-fs

For now it's not available as a package since it requires this PR (https://github.com/ralphbean/taskw/pull/160) to be merged first.

I'll close this ticket once I merge it and have a package ready. Until then, if you wantto try it you have to checkout that branch and point the taskw reference in pyproject.toml to a locally downloaded version of taskw that uses my taskw remote (https://github.com/bergercookie/taskw)

**Comment by OddBloke** [comment]
I've been looking at syncing GCal meetings into a TW tag: I've noticed that the end time of meetings is used to set the due date in TW, and of course I'd prefer the _start_ time to be the due date for this use case.

Will that use case be enabled by the linked branch? (Shall I file a separate issue?)

**Comment by bergercookie** [comment]
I haven't implemented that in the said branch. it adds options for using `scheduled` dates instead of `due` but that also sets the end date.

It would be best to file this as a separate ticket :)

**Comment by bcohen44** [comment]
@bergercookie could I get some more details on exactly what to do here:

> , if you wantto try it you have to checkout that branch and point the taskw reference in pyproject.toml to a locally downloaded version of taskw that uses my taskw remote

I did already update to to the taskw `develop` branch, just the steps after.

**Comment by bergercookie** [comment]
This is now supported.


```
  --prefer-scheduled-date         Prefer using the "scheduled" date field
                                  instead of the "due" date if the former is
                                  available
```

Since the repo and the associated PyPI package is renamed to syncall, please remove the former one and install the latest version of syncall as follows:

```
pip3 uninstall taskwarrior-syncall && pip3 install --upgrade syncall
```
