### ISSUE TITLE
[Feature Request] Exclude/ignore "other side" events (by title)

### ISSUE THREAD

**Issue by OddBloke** [bergercookie/syncall#45]
I'm looking at using `tw_gcal_sync` to sync my upcoming meetings into taskwarrior. I have some events on my calendar that I will never want synced (e.g. "Lunch (via Clockwise)").

I would like to be able to specify a list of substrings (e.g. "via Clockwise") whose presence will cause `tw_gcal_sync` to exclude an event from the set considered to be present in GCal, so they will never be synced.

**Comment by bergercookie** [comment]
This is a fair request :)
This isn't currently implemented so if you want to have a go, let me know, otherwise I may look into it, but can't promise on an ETA

By the way, even though `tw_gcal_sync` is pretty stable by now, nevertheless I would suggest to consider a way to bring your synchronization to a clean slate if needed. For example in my case, I always sync a subset of my taskwarrior tasks (thouse with `+remindme`) to a completely separate google calendar so, if I wanted to reset the synchronization, I just delete that calendar and delete all the files under `~/.config/taskwarrior_syncall/...` and run `tw_gcal_sync ...` again.

I suppose that you could resort to something similar (e.g., `task rm +special_tag_of_synced_items && rm -rf ~/.config/taskwarrior_syncall/...`).

**Comment by bergercookie** [comment]
OK,  2+ years for an update but, I did have a shot at implementing this but it was too messy to be honest for the potential added value, and I think there are better alternatives, like keeping the events to be ignored in a separate calendar altogether.

Unfortunately I'll have to close this.
