### ISSUE TITLE
[BUG] Tasks originally created in Google Calendar don't have UUID, task status in their body - cannot complete them from Google Calendar Side

### ISSUE THREAD

**Issue by bcohen44** [bergercookie/syncall#48]
Not sure if this is a bug.
When I enter an event in GCal, then sync, it gets to TW with the proper due date and time.
Then add a status: completed on the calendar event description, it does not sync make the TW task done.  I even manually added the `uuid: ` to the description in the event, sync, same thing.

Also, even TW originated tasks, when editing the sync'd event status in the description does not make the TW task done.

**Comment by bcohen44** [comment]
You can see that a change is detected when I change the GCal event status: to completed.  But nothing is actually changed in the TW task., no is the checkbox emoji added to the event.

```
8:00:22.83 | INFO     	| Detecting changes from Tw...
08:00:22.83 | DEBUG    	| 

New Items:      0
Modified Items: 0
Deleted Item:   0

08:00:22.83 | DEBUG    	| Fetching Gcal item for id -> 2hsmablsegmci016kctellageq
08:00:22.83 | INFO     	| [Gcal] Updating item [foo10     ] at Tw...
08:00:23.20 | WARNING  	| 

Google Calendar
---------------
	* Items created: 0
	* Items updated: 0
	* Items deleted: 0

Taskwarrior
-----------
	* Items created: 0
	* Items updated: 1
	* Items deleted: 0
```

**Comment by bergercookie** [comment]
Hi @bcohen44 ,

For events that are created originally in Google Calendar, yes, this is a bug.
This is because, if they're originally created there, they're pulled into taskwarrior, but their Google Calendar description is never updated.

If, after the first synchronization, you make an edit from the taskwarrior side and sync again, then it will edit the description of the Google calendar event and then you should be able to change the `status: pending` line to `status: completed` to resolve the task

> Also, even TW originated tasks, when editing the sync'd event status in the description does not make the TW task done.

I can't repro this for TW originated tasks. Please try this again with the latest `syncall` `1.4` version and open a separate issue if it exists.

**Comment by bergercookie** [comment]
Looking at this again, I think I'm going to close it. This isn't straightforward to solve, at least not in a generic way and on top of that, IMHO it's not a critical one to fix either

I'm open to suggestions though and I can reopen in that case
