### ISSUE TITLE
TW sync with caldav doesn't distinguish completed tasks

### ISSUE THREAD

**Issue by guyjames** [bergercookie/syncall#74]
I have tried to resolve this issue myself by trial and error and by looking through the Issues here but have not been able to.

I am syncing Taskwarrior with Nextcloud Tasks (caldav protocol).

Due to the previous takedown of freecinc.com which I was using before, I haven't used TW for over 30 days (this is relevant later).

The sync between TW and caldav works perfectly except that I am only able to sync --all tasks — this includes all completed tasks in TW, which then end up in my to do list, but without completed status, i.e. **it is not passing their completed status along to caldav during the sync.** Due to not having used TW in the last 30 days that filter is not useful either.

I have been able to hack my way around it by giving all pending tasks a tag of "pending" and then only syncing those, but this introduces another step into the process which I would rather not have to do. I generally don't assign projects or tags to tasks unless they specifically need one.

I tried deleting the completed.data file in the .task folder but this didn't help, the completed tasks still appeared in the final sync from somewhere else.

Any help is appreciated.

**Comment by saccarosium** [comment]
Having the same issue here. But after some investigation turns pit it's probably a problem with how nextcloud integrates with caldav. On other application, like 2do, there is no isses (syncong with my nextcloud instance).

**Comment by bergercookie** [comment]
Hi both,

Thanks for reporting.
Yes, I'm aware of this issue.

In general the "sync only modified tasks of last 30 days" is quite restrictive and also doesn't work with cases like this. I'm looking to extend it in the next few weeks to allow for ranges and to allow for tasks with due dates instead of modified dates

**Comment by bertrand-benoit** [comment]
Any news?

**Comment by bjornfor** [comment]
Not stale.

**Comment by bergercookie** [comment]
> The sync between TW and caldav works perfectly except that I am only able to sync --all tasks — this includes all completed tasks in TW, which then end up in my to do list

You should be able to use `f` / `--tw-filter` to specify with more granularity the tasks that you're looking to sync from the taskwarrior side.

>  this includes all completed tasks in TW, which then end up in my to do list, but without completed status, i.e. it is not passing their completed status along to caldav during the sync.

I don't quite remember the state of the tool at the time of the issue creation but I don't think that's the current behavior - if a task is included in the TW filter (in your case, if is modified in the last 30 days) then it synced - if it isn't, then it shouldn't be taken in account at all and also if it was synced in earlier runs, because `tw_caldav_sync` cannot currently find it, it will probably issue its deletion on the CalDAV side as well.

In any case I think the `-f` flag should suit your needs much better and you should be able to tune what tasks to sync.

I'll close this as completed but if I haven't understood the issue or if it persists we can re-open

**Comment by bergercookie** [comment]
@guyjames please give it a go with the latest v1.8.8 and let me know how it works.

**Comment by guyjames** [comment]
ok thanks. I am not using the caldav thing any more but I'll go back and give it another try now. but it might be a little while before I can report back.
