### ISSUE TITLE
Tw<->Gcal: Ignoring tasks with a particular tag for sync

### ISSUE THREAD

**Issue by AbstractGeek** [bergercookie/syncall#81]
It would be nice to be able to sync tasks which do not allow a particular tag, like -tag. It will allow selective syncing of tasks with particular tags with different calendars (like tw_gcal_syn with +shared goes to a particular calendar, whereas tw_gcal_syn with -shared all go to a different calendar).

**Comment by bergercookie** [comment]
This should be possible when we switch to `tasklib` - see #65

**Comment by bergercookie** [comment]
Hi @AbstractGeek 

This should now be supported across all the apps in this repo that interact with Taskwarrior. Use the custom taskwarrior filtering in order to specify that you don't want to synchronize tags of a particular tag

```
tw_gcal_sync -f "-tag_to_skip" -t tag_to_include -c some_cal
```

This feature should work on latest master - commit https://github.com/bergercookie/syncall/commit/0893f12870aff5242118993c70f61bbfc85544cb - and should make its way to a pypi release in the coming week(s)
